# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lais/Documentos/ROB307/rob_307/Count/hw_ip_only/hw_ip_only.srcs/sources_1/bd/count_ip/ip/count_ip_axi_dma_0_1/count_ip_axi_dma_0_1.xci
# IP: The module: 'count_ip_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lais/Documentos/ROB307/rob_307/Count/hw_ip_only/hw_ip_only.srcs/sources_1/bd/count_ip/ip/count_ip_axi_dma_0_1/count_ip_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'count_ip_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lais/Documentos/ROB307/rob_307/Count/hw_ip_only/hw_ip_only.srcs/sources_1/bd/count_ip/ip/count_ip_axi_dma_0_1/count_ip_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'count_ip_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lais/Documentos/ROB307/rob_307/Count/hw_ip_only/hw_ip_only.srcs/sources_1/bd/count_ip/ip/count_ip_axi_dma_0_1/count_ip_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'count_ip_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lais/Documentos/ROB307/rob_307/Count/hw_ip_only/hw_ip_only.srcs/sources_1/bd/count_ip/ip/count_ip_axi_dma_0_1/count_ip_axi_dma_0_1.xci
# IP: The module: 'count_ip_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lais/Documentos/ROB307/rob_307/Count/hw_ip_only/hw_ip_only.srcs/sources_1/bd/count_ip/ip/count_ip_axi_dma_0_1/count_ip_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'count_ip_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lais/Documentos/ROB307/rob_307/Count/hw_ip_only/hw_ip_only.srcs/sources_1/bd/count_ip/ip/count_ip_axi_dma_0_1/count_ip_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'count_ip_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lais/Documentos/ROB307/rob_307/Count/hw_ip_only/hw_ip_only.srcs/sources_1/bd/count_ip/ip/count_ip_axi_dma_0_1/count_ip_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'count_ip_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
