// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XCOUNT_H
#define XCOUNT_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xcount_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_bus_BaseAddress;
} XCount_Config;
#endif

typedef struct {
    u32 Ctrl_bus_BaseAddress;
    u32 IsReady;
} XCount;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XCount_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XCount_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XCount_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XCount_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XCount_Initialize(XCount *InstancePtr, u16 DeviceId);
XCount_Config* XCount_LookupConfig(u16 DeviceId);
int XCount_CfgInitialize(XCount *InstancePtr, XCount_Config *ConfigPtr);
#else
int XCount_Initialize(XCount *InstancePtr, const char* InstanceName);
int XCount_Release(XCount *InstancePtr);
#endif

void XCount_Start(XCount *InstancePtr);
u32 XCount_IsDone(XCount *InstancePtr);
u32 XCount_IsIdle(XCount *InstancePtr);
u32 XCount_IsReady(XCount *InstancePtr);
void XCount_EnableAutoRestart(XCount *InstancePtr);
void XCount_DisableAutoRestart(XCount *InstancePtr);

void XCount_Set_size(XCount *InstancePtr, u32 Data);
u32 XCount_Get_size(XCount *InstancePtr);
void XCount_Set_filter(XCount *InstancePtr, u32 Data);
u32 XCount_Get_filter(XCount *InstancePtr);

void XCount_InterruptGlobalEnable(XCount *InstancePtr);
void XCount_InterruptGlobalDisable(XCount *InstancePtr);
void XCount_InterruptEnable(XCount *InstancePtr, u32 Mask);
void XCount_InterruptDisable(XCount *InstancePtr, u32 Mask);
void XCount_InterruptClear(XCount *InstancePtr, u32 Mask);
u32 XCount_InterruptGetEnabled(XCount *InstancePtr);
u32 XCount_InterruptGetStatus(XCount *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
