// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xquicksortiterative.h"

extern XQuicksortiterative_Config XQuicksortiterative_ConfigTable[];

XQuicksortiterative_Config *XQuicksortiterative_LookupConfig(u16 DeviceId) {
	XQuicksortiterative_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XQUICKSORTITERATIVE_NUM_INSTANCES; Index++) {
		if (XQuicksortiterative_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XQuicksortiterative_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XQuicksortiterative_Initialize(XQuicksortiterative *InstancePtr, u16 DeviceId) {
	XQuicksortiterative_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XQuicksortiterative_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XQuicksortiterative_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

