// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xquicksortiterative.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XQuicksortiterative_CfgInitialize(XQuicksortiterative *InstancePtr, XQuicksortiterative_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XQuicksortiterative_Start(XQuicksortiterative *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XQuicksortiterative_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_AP_CTRL) & 0x80;
    XQuicksortiterative_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XQuicksortiterative_IsDone(XQuicksortiterative *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XQuicksortiterative_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XQuicksortiterative_IsIdle(XQuicksortiterative *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XQuicksortiterative_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XQuicksortiterative_IsReady(XQuicksortiterative *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XQuicksortiterative_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XQuicksortiterative_EnableAutoRestart(XQuicksortiterative *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XQuicksortiterative_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_AP_CTRL, 0x80);
}

void XQuicksortiterative_DisableAutoRestart(XQuicksortiterative *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XQuicksortiterative_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_AP_CTRL, 0);
}

void XQuicksortiterative_InterruptGlobalEnable(XQuicksortiterative *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XQuicksortiterative_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_GIE, 1);
}

void XQuicksortiterative_InterruptGlobalDisable(XQuicksortiterative *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XQuicksortiterative_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_GIE, 0);
}

void XQuicksortiterative_InterruptEnable(XQuicksortiterative *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XQuicksortiterative_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_IER);
    XQuicksortiterative_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_IER, Register | Mask);
}

void XQuicksortiterative_InterruptDisable(XQuicksortiterative *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XQuicksortiterative_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_IER);
    XQuicksortiterative_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_IER, Register & (~Mask));
}

void XQuicksortiterative_InterruptClear(XQuicksortiterative *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XQuicksortiterative_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_ISR, Mask);
}

u32 XQuicksortiterative_InterruptGetEnabled(XQuicksortiterative *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XQuicksortiterative_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_IER);
}

u32 XQuicksortiterative_InterruptGetStatus(XQuicksortiterative *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XQuicksortiterative_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVE_CTRL_BUS_ADDR_ISR);
}

