// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xquicksortiterativev2.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XQuicksortiterativev2_CfgInitialize(XQuicksortiterativev2 *InstancePtr, XQuicksortiterativev2_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XQuicksortiterativev2_Start(XQuicksortiterativev2 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XQuicksortiterativev2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_AP_CTRL) & 0x80;
    XQuicksortiterativev2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XQuicksortiterativev2_IsDone(XQuicksortiterativev2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XQuicksortiterativev2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XQuicksortiterativev2_IsIdle(XQuicksortiterativev2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XQuicksortiterativev2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XQuicksortiterativev2_IsReady(XQuicksortiterativev2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XQuicksortiterativev2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XQuicksortiterativev2_EnableAutoRestart(XQuicksortiterativev2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XQuicksortiterativev2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_AP_CTRL, 0x80);
}

void XQuicksortiterativev2_DisableAutoRestart(XQuicksortiterativev2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XQuicksortiterativev2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_AP_CTRL, 0);
}

void XQuicksortiterativev2_Set_size(XQuicksortiterativev2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XQuicksortiterativev2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_SIZE_DATA, Data);
}

u32 XQuicksortiterativev2_Get_size(XQuicksortiterativev2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XQuicksortiterativev2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_SIZE_DATA);
    return Data;
}

void XQuicksortiterativev2_Set_pivot(XQuicksortiterativev2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XQuicksortiterativev2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_PIVOT_DATA, Data);
}

u32 XQuicksortiterativev2_Get_pivot(XQuicksortiterativev2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XQuicksortiterativev2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_PIVOT_DATA);
    return Data;
}

void XQuicksortiterativev2_InterruptGlobalEnable(XQuicksortiterativev2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XQuicksortiterativev2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_GIE, 1);
}

void XQuicksortiterativev2_InterruptGlobalDisable(XQuicksortiterativev2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XQuicksortiterativev2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_GIE, 0);
}

void XQuicksortiterativev2_InterruptEnable(XQuicksortiterativev2 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XQuicksortiterativev2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_IER);
    XQuicksortiterativev2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_IER, Register | Mask);
}

void XQuicksortiterativev2_InterruptDisable(XQuicksortiterativev2 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XQuicksortiterativev2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_IER);
    XQuicksortiterativev2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_IER, Register & (~Mask));
}

void XQuicksortiterativev2_InterruptClear(XQuicksortiterativev2 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XQuicksortiterativev2_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_ISR, Mask);
}

u32 XQuicksortiterativev2_InterruptGetEnabled(XQuicksortiterativev2 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XQuicksortiterativev2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_IER);
}

u32 XQuicksortiterativev2_InterruptGetStatus(XQuicksortiterativev2 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XQuicksortiterativev2_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XQUICKSORTITERATIVEV2_CTRL_BUS_ADDR_ISR);
}

