// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XQUICKSORTITERATIVEV2_H
#define XQUICKSORTITERATIVEV2_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xquicksortiterativev2_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_bus_BaseAddress;
} XQuicksortiterativev2_Config;
#endif

typedef struct {
    u32 Ctrl_bus_BaseAddress;
    u32 IsReady;
} XQuicksortiterativev2;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XQuicksortiterativev2_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XQuicksortiterativev2_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XQuicksortiterativev2_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XQuicksortiterativev2_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XQuicksortiterativev2_Initialize(XQuicksortiterativev2 *InstancePtr, u16 DeviceId);
XQuicksortiterativev2_Config* XQuicksortiterativev2_LookupConfig(u16 DeviceId);
int XQuicksortiterativev2_CfgInitialize(XQuicksortiterativev2 *InstancePtr, XQuicksortiterativev2_Config *ConfigPtr);
#else
int XQuicksortiterativev2_Initialize(XQuicksortiterativev2 *InstancePtr, const char* InstanceName);
int XQuicksortiterativev2_Release(XQuicksortiterativev2 *InstancePtr);
#endif

void XQuicksortiterativev2_Start(XQuicksortiterativev2 *InstancePtr);
u32 XQuicksortiterativev2_IsDone(XQuicksortiterativev2 *InstancePtr);
u32 XQuicksortiterativev2_IsIdle(XQuicksortiterativev2 *InstancePtr);
u32 XQuicksortiterativev2_IsReady(XQuicksortiterativev2 *InstancePtr);
void XQuicksortiterativev2_EnableAutoRestart(XQuicksortiterativev2 *InstancePtr);
void XQuicksortiterativev2_DisableAutoRestart(XQuicksortiterativev2 *InstancePtr);

void XQuicksortiterativev2_Set_size(XQuicksortiterativev2 *InstancePtr, u32 Data);
u32 XQuicksortiterativev2_Get_size(XQuicksortiterativev2 *InstancePtr);
void XQuicksortiterativev2_Set_pivot(XQuicksortiterativev2 *InstancePtr, u32 Data);
u32 XQuicksortiterativev2_Get_pivot(XQuicksortiterativev2 *InstancePtr);

void XQuicksortiterativev2_InterruptGlobalEnable(XQuicksortiterativev2 *InstancePtr);
void XQuicksortiterativev2_InterruptGlobalDisable(XQuicksortiterativev2 *InstancePtr);
void XQuicksortiterativev2_InterruptEnable(XQuicksortiterativev2 *InstancePtr, u32 Mask);
void XQuicksortiterativev2_InterruptDisable(XQuicksortiterativev2 *InstancePtr, u32 Mask);
void XQuicksortiterativev2_InterruptClear(XQuicksortiterativev2 *InstancePtr, u32 Mask);
u32 XQuicksortiterativev2_InterruptGetEnabled(XQuicksortiterativev2 *InstancePtr);
u32 XQuicksortiterativev2_InterruptGetStatus(XQuicksortiterativev2 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
