// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdokmean.h"

extern XDokmean_Config XDokmean_ConfigTable[];

XDokmean_Config *XDokmean_LookupConfig(u16 DeviceId) {
	XDokmean_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDOKMEAN_NUM_INSTANCES; Index++) {
		if (XDokmean_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDokmean_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDokmean_Initialize(XDokmean *InstancePtr, u16 DeviceId) {
	XDokmean_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDokmean_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDokmean_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

