# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hw_one_ip/hw_one_ip.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_one_ip || ORIG_REF_NAME==hw_one_ip} -quiet] -quiet

# IP: bd/hw_one_ip/ip/hw_one_ip_processing_system7_0_0/hw_one_ip_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_one_ip_processing_system7_0_0 || ORIG_REF_NAME==hw_one_ip_processing_system7_0_0} -quiet] -quiet

# IP: bd/hw_one_ip/ip/hw_one_ip_quickSortIterative_0_0/hw_one_ip_quickSortIterative_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_one_ip_quickSortIterative_0_0 || ORIG_REF_NAME==hw_one_ip_quickSortIterative_0_0} -quiet] -quiet

# IP: bd/hw_one_ip/ip/hw_one_ip_axi_dma_0_0/hw_one_ip_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_one_ip_axi_dma_0_0 || ORIG_REF_NAME==hw_one_ip_axi_dma_0_0} -quiet] -quiet

# IP: bd/hw_one_ip/ip/hw_one_ip_axi_smc_0/hw_one_ip_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_one_ip_axi_smc_0 || ORIG_REF_NAME==hw_one_ip_axi_smc_0} -quiet] -quiet

# IP: bd/hw_one_ip/ip/hw_one_ip_rst_ps7_0_100M_0/hw_one_ip_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_one_ip_rst_ps7_0_100M_0 || ORIG_REF_NAME==hw_one_ip_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/hw_one_ip/ip/hw_one_ip_ps7_0_axi_periph_0/hw_one_ip_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_one_ip_ps7_0_axi_periph_0 || ORIG_REF_NAME==hw_one_ip_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hw_one_ip/ip/hw_one_ip_axi_timer_0_0/hw_one_ip_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_one_ip_axi_timer_0_0 || ORIG_REF_NAME==hw_one_ip_axi_timer_0_0} -quiet] -quiet

# IP: bd/hw_one_ip/ip/hw_one_ip_xlconcat_0_0/hw_one_ip_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_one_ip_xlconcat_0_0 || ORIG_REF_NAME==hw_one_ip_xlconcat_0_0} -quiet] -quiet

# IP: bd/hw_one_ip/ip/hw_one_ip_xbar_0/hw_one_ip_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_one_ip_xbar_0 || ORIG_REF_NAME==hw_one_ip_xbar_0} -quiet] -quiet

# IP: bd/hw_one_ip/ip/hw_one_ip_auto_pc_0/hw_one_ip_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_one_ip_auto_pc_0 || ORIG_REF_NAME==hw_one_ip_auto_pc_0} -quiet] -quiet

# XDC: bd/hw_one_ip/hw_one_ip_ooc.xdc
