// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcount.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCount_CfgInitialize(XCount *InstancePtr, XCount_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCount_Start(XCount *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCount_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_AP_CTRL) & 0x80;
    XCount_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCount_IsDone(XCount *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCount_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCount_IsIdle(XCount *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCount_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCount_IsReady(XCount *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCount_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCount_EnableAutoRestart(XCount *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCount_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_AP_CTRL, 0x80);
}

void XCount_DisableAutoRestart(XCount *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCount_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_AP_CTRL, 0);
}

void XCount_Set_size(XCount *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCount_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_SIZE_DATA, Data);
}

u32 XCount_Get_size(XCount *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCount_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_SIZE_DATA);
    return Data;
}

void XCount_Set_filter(XCount *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCount_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_FILTER_DATA, Data);
}

u32 XCount_Get_filter(XCount *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCount_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_FILTER_DATA);
    return Data;
}

void XCount_InterruptGlobalEnable(XCount *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCount_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_GIE, 1);
}

void XCount_InterruptGlobalDisable(XCount *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCount_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_GIE, 0);
}

void XCount_InterruptEnable(XCount *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCount_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_IER);
    XCount_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_IER, Register | Mask);
}

void XCount_InterruptDisable(XCount *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCount_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_IER);
    XCount_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_IER, Register & (~Mask));
}

void XCount_InterruptClear(XCount *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCount_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_ISR, Mask);
}

u32 XCount_InterruptGetEnabled(XCount *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCount_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_IER);
}

u32 XCount_InterruptGetStatus(XCount *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCount_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCOUNT_CTRL_BUS_ADDR_ISR);
}

