// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcount.h"

extern XCount_Config XCount_ConfigTable[];

XCount_Config *XCount_LookupConfig(u16 DeviceId) {
	XCount_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCOUNT_NUM_INSTANCES; Index++) {
		if (XCount_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XCount_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XCount_Initialize(XCount *InstancePtr, u16 DeviceId) {
	XCount_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XCount_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XCount_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

