# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lais/Documents/ROB307/rob_307/dijkstra/hw_ip_only/hw_ip_only.srcs/sources_1/bd/dijkstra_ip/ip/dijkstra_ip_rst_ps7_0_100M_0/dijkstra_ip_rst_ps7_0_100M_0.xci
# IP: The module: 'dijkstra_ip_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lais/Documents/ROB307/rob_307/dijkstra/hw_ip_only/hw_ip_only.srcs/sources_1/bd/dijkstra_ip/ip/dijkstra_ip_rst_ps7_0_100M_0/dijkstra_ip_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dijkstra_ip_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lais/Documents/ROB307/rob_307/dijkstra/hw_ip_only/hw_ip_only.srcs/sources_1/bd/dijkstra_ip/ip/dijkstra_ip_rst_ps7_0_100M_0/dijkstra_ip_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dijkstra_ip_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lais/Documents/ROB307/rob_307/dijkstra/hw_ip_only/hw_ip_only.srcs/sources_1/bd/dijkstra_ip/ip/dijkstra_ip_rst_ps7_0_100M_0/dijkstra_ip_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dijkstra_ip_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lais/Documents/ROB307/rob_307/dijkstra/hw_ip_only/hw_ip_only.srcs/sources_1/bd/dijkstra_ip/ip/dijkstra_ip_rst_ps7_0_100M_0/dijkstra_ip_rst_ps7_0_100M_0.xci
# IP: The module: 'dijkstra_ip_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lais/Documents/ROB307/rob_307/dijkstra/hw_ip_only/hw_ip_only.srcs/sources_1/bd/dijkstra_ip/ip/dijkstra_ip_rst_ps7_0_100M_0/dijkstra_ip_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dijkstra_ip_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lais/Documents/ROB307/rob_307/dijkstra/hw_ip_only/hw_ip_only.srcs/sources_1/bd/dijkstra_ip/ip/dijkstra_ip_rst_ps7_0_100M_0/dijkstra_ip_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dijkstra_ip_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lais/Documents/ROB307/rob_307/dijkstra/hw_ip_only/hw_ip_only.srcs/sources_1/bd/dijkstra_ip/ip/dijkstra_ip_rst_ps7_0_100M_0/dijkstra_ip_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dijkstra_ip_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
