// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XDOKMEAN_H
#define XDOKMEAN_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xdokmean_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Crtl_bus_BaseAddress;
} XDokmean_Config;
#endif

typedef struct {
    u32 Crtl_bus_BaseAddress;
    u32 IsReady;
} XDokmean;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XDokmean_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XDokmean_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XDokmean_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XDokmean_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XDokmean_Initialize(XDokmean *InstancePtr, u16 DeviceId);
XDokmean_Config* XDokmean_LookupConfig(u16 DeviceId);
int XDokmean_CfgInitialize(XDokmean *InstancePtr, XDokmean_Config *ConfigPtr);
#else
int XDokmean_Initialize(XDokmean *InstancePtr, const char* InstanceName);
int XDokmean_Release(XDokmean *InstancePtr);
#endif

void XDokmean_Start(XDokmean *InstancePtr);
u32 XDokmean_IsDone(XDokmean *InstancePtr);
u32 XDokmean_IsIdle(XDokmean *InstancePtr);
u32 XDokmean_IsReady(XDokmean *InstancePtr);
void XDokmean_EnableAutoRestart(XDokmean *InstancePtr);
void XDokmean_DisableAutoRestart(XDokmean *InstancePtr);

void XDokmean_Set_gain(XDokmean *InstancePtr, u32 Data);
u32 XDokmean_Get_gain(XDokmean *InstancePtr);

void XDokmean_InterruptGlobalEnable(XDokmean *InstancePtr);
void XDokmean_InterruptGlobalDisable(XDokmean *InstancePtr);
void XDokmean_InterruptEnable(XDokmean *InstancePtr, u32 Mask);
void XDokmean_InterruptDisable(XDokmean *InstancePtr, u32 Mask);
void XDokmean_InterruptClear(XDokmean *InstancePtr, u32 Mask);
u32 XDokmean_InterruptGetEnabled(XDokmean *InstancePtr);
u32 XDokmean_InterruptGetStatus(XDokmean *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
