# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lais/Documentos/ROB307/rob_307/quicksort/hw_one_ip/hw_one_ip.srcs/sources_1/bd/hw_one_ip/ip/hw_one_ip_auto_pc_0/hw_one_ip_auto_pc_0.xci
# IP: The module: 'hw_one_ip_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lais/Documentos/ROB307/rob_307/quicksort/hw_one_ip/hw_one_ip.srcs/sources_1/bd/hw_one_ip/ip/hw_one_ip_auto_pc_0/hw_one_ip_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_one_ip_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/lais/Documentos/ROB307/rob_307/quicksort/hw_one_ip/hw_one_ip.srcs/sources_1/bd/hw_one_ip/ip/hw_one_ip_auto_pc_0/hw_one_ip_auto_pc_0.xci
# IP: The module: 'hw_one_ip_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lais/Documentos/ROB307/rob_307/quicksort/hw_one_ip/hw_one_ip.srcs/sources_1/bd/hw_one_ip/ip/hw_one_ip_auto_pc_0/hw_one_ip_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_one_ip_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
