# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/count_ip/count_ip.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip || ORIG_REF_NAME==count_ip} -quiet] -quiet

# IP: bd/count_ip/ip/count_ip_processing_system7_0_0/count_ip_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip_processing_system7_0_0 || ORIG_REF_NAME==count_ip_processing_system7_0_0} -quiet] -quiet

# IP: bd/count_ip/ip/count_ip_axi_timer_0_0/count_ip_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip_axi_timer_0_0 || ORIG_REF_NAME==count_ip_axi_timer_0_0} -quiet] -quiet

# IP: bd/count_ip/ip/count_ip_axi_dma_0_1/count_ip_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip_axi_dma_0_1 || ORIG_REF_NAME==count_ip_axi_dma_0_1} -quiet] -quiet

# IP: bd/count_ip/ip/count_ip_rst_ps7_0_100M_0/count_ip_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip_rst_ps7_0_100M_0 || ORIG_REF_NAME==count_ip_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/count_ip/ip/count_ip_ps7_0_axi_periph_0/count_ip_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip_ps7_0_axi_periph_0 || ORIG_REF_NAME==count_ip_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/count_ip/ip/count_ip_xlconcat_0_0/count_ip_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip_xlconcat_0_0 || ORIG_REF_NAME==count_ip_xlconcat_0_0} -quiet] -quiet

# IP: bd/count_ip/ip/count_ip_xbar_0/count_ip_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip_xbar_0 || ORIG_REF_NAME==count_ip_xbar_0} -quiet] -quiet

# IP: bd/count_ip/ip/count_ip_axi_interconnect_0_0/count_ip_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip_axi_interconnect_0_0 || ORIG_REF_NAME==count_ip_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/count_ip/ip/count_ip_xbar_1/count_ip_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip_xbar_1 || ORIG_REF_NAME==count_ip_xbar_1} -quiet] -quiet

# IP: bd/count_ip/ip/count_ip_Count_0_0/count_ip_Count_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip_Count_0_0 || ORIG_REF_NAME==count_ip_Count_0_0} -quiet] -quiet

# IP: bd/count_ip/ip/count_ip_auto_pc_1/count_ip_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip_auto_pc_1 || ORIG_REF_NAME==count_ip_auto_pc_1} -quiet] -quiet

# IP: bd/count_ip/ip/count_ip_auto_us_1/count_ip_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip_auto_us_1 || ORIG_REF_NAME==count_ip_auto_us_1} -quiet] -quiet

# IP: bd/count_ip/ip/count_ip_auto_us_0/count_ip_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip_auto_us_0 || ORIG_REF_NAME==count_ip_auto_us_0} -quiet] -quiet

# IP: bd/count_ip/ip/count_ip_auto_pc_0/count_ip_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==count_ip_auto_pc_0 || ORIG_REF_NAME==count_ip_auto_pc_0} -quiet] -quiet

# XDC: bd/count_ip/count_ip_ooc.xdc
