// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xquicksortiterativev2.h"

extern XQuicksortiterativev2_Config XQuicksortiterativev2_ConfigTable[];

XQuicksortiterativev2_Config *XQuicksortiterativev2_LookupConfig(u16 DeviceId) {
	XQuicksortiterativev2_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XQUICKSORTITERATIVEV2_NUM_INSTANCES; Index++) {
		if (XQuicksortiterativev2_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XQuicksortiterativev2_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XQuicksortiterativev2_Initialize(XQuicksortiterativev2 *InstancePtr, u16 DeviceId) {
	XQuicksortiterativev2_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XQuicksortiterativev2_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XQuicksortiterativev2_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

